lane :beta do
  gradle(
    task: "assembleRelease"
  )

  # APK 파일 경로 지정
  apk_path = "/Users/gilzako/WebstormProjects/gas4management/android/app/build/outputs/apk/release/app-release.apk"
  #apk_path = "/Users/gilza/joatech/gas4/android/app/build/outputs/apk/release/app-release.apk"




  # Firebase App Distribution 업로드
  firebase_app_distribution(
    app: "1:80656391423:android:ebac598125c05cb6d300ca",
    groups: "aaaaa",
    release_notes: "
              상세 중복 로딩 제거/개선.!
    ",
    apk_path: apk_path  # 명확하게 경로 지정
  )
end

lane :play do
  gradle(
    task: "bundleRelease"
  )

  # AAB 파일 경로 지정
  aab_path = "/Users/gilzako/WebstormProjects/gas4management/android/app/build/outputs/bundle/release/app-release.aab"
  #aab_path = "/Users/gilza/joatech/gas4/android/app/build/outputs/bundle/release/app-release.aab"

  # Google Play Store 프로덕션 배포
  upload_to_play_store(
    track: "production",  # 프로덕션 릴리즈
    aab: aab_path,  # AAB 파일 업로드
    json_key: "fastlane/play2.json",  # Google API 인증 JSON 파일 경로
    package_name: "com.joainfo.gasmaxeye2025",  # 앱 패키지명
    skip_upload_apk: true ,
    skip_upload_metadata: false, # 필요 시 true로 변경
    validate_only: false, # 실제 업로드 실행 (테스트 모드 아님)
    skip_upload_changelogs: false
  )

  # 릴리즈 노트를 changelog 파일에 작성 (폴더가 없으면 생성)
  changelog_path = "fastlane/metadata/android/en-US/changelogs/default.txt"
  FileUtils.mkdir_p(File.dirname(changelog_path)) unless File.directory?(File.dirname(changelog_path))
  File.write(changelog_path, "발긴기 번호가 없는 경우 애러메세지 처리! ")
end


#npx cap sync && (cd android && fastlane beta) && cd -
